### ISSUE TITLE
telethon docker说明可能有误

### ISSUE THREAD

**Issue by cc0cc0cc0** [kissyouhunter/Dockerfiles#1]
从docker hub过来的， https://hub.docker.com/r/kissyouhunter/telethon    这个镜像是您做的吧，要是弄错了就打扰了。目前这个镜像我这使用正常，谢谢了，十分好使。不过在跟着指导使用的过程发现，定时任务可能描述有误，linux一般的定时任务都是5个星的，我看你的描述是6个星的，在我的N1设备上6个星无法生效的，5个星就没有问题。

**Comment by kissyouhunter** [comment]
6个星的第一个是表示秒，一般是可省略的。
可能有些系统无法识别秒，我去修改一下。
